name: meditation
description: Flutter application built on top of contra wireframe kit.


version: 1.0.0+1


environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  flutter_staggered_grid_view: ^0.3.0
  flutter_time_picker_spinner: ^1.0.6+1
  charts_flutter: ^0.9.0
  fl_chart: ^0.10.0
  google_maps_flutter: ^0.5.28+1
  flutter_swiper: ^1.1.6
  flutter_xlider: ^3.1.1
  font_awesome_flutter: ^8.7.0
  feather_icons_flutter: ^4.7.4
  flutter_feather_icons: ^1.0.3
  audioplayer: ^0.8.1
  path_provider: ^1.6.11
  http: ^0.12.1





flutter:

  assets:
    - images/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/images/shopping/
    

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
  uses-material-design: true

